### ISSUE TITLE
Problems about removing deplicated mappings

### ISSUE THREAD

**Issue by vanessayang0927** [chhylp123/BitMapperBS#3]
Hi,
I tested BitMapperBS recently, it was really a very high-efficiency aligner.
I runned the software successfully, but found it didn't include the step of removing duplicated mappings compared with other sodtware like Bismark, BSmap.
And I wanted to know what software do you suggest to remove those duplicated mapping reads.

**Comment by chhylp123** [comment]
> Hi,
> I tested BitMapperBS recently, it was really a very high-efficiency aligner.
> I runned the software successfully, but found it didn't include the step of removing duplicated mappings compared with other sodtware like Bismark, BSmap.
> And I wanted to know what software do you suggest to remove those duplicated mapping reads.

Now you can use MethylDackel (https://github.com/dpryan79/methyldackel) to remove duplicated mapping reads and extract methylation information. In default, MethylDackel can remove the duplicated reads as well as the overlapping paired-end reads.


For example, if you have the the ouput file of BitMapperBS named output.sam:

(1) Converting SAM directly to a sorted BAM file;
samtools sort -@ 8 -o output.bam output.sam (SAMtools version 1.3 or newer, using 8 CPU threads)
or
samtools view -bS output.sam | samtools sort - -o output.bam (SAMtools version 1.2 or older)

(2)Extract methylation information using 8 CPU threads:
MethylDackel extract reference_genome.fa output.bam -@ 8

I am now also developing a new methylation extract algorithm. For the next several days, the new version of BitMapperBS will be resleased to directly output the methylation information rather than .sam or .bam.

Thank you for the interest in BitMapperBS.

**Comment by vanessayang0927** [comment]
It ran successfully and I encountered no errors. The issue can be closed.


Thanks for your help and looking forward to the upgraded BitMapperBS !
